name: CI/CD Pipeline for Product Service

on:
  push:
    paths:
      - 'product-service/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        cd product-service
        docker build -t miqbal38/ims-app-microservices-product-service:latest .
        docker push miqbal38/ims-app-microservices-product-service:latest

